[package]
name = "lune-std-ffi"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/lune-org/lune"
description = "Lune standard library - FFI"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
mlua = { version = "0.11.6", features = ["luau"] }
mlua-sys = { version = "0.10.0", features = ["luau"] }
num = "0.4.3"
dlopen2 = "0.7.0"
libc = "0.2.162"

libffi = "3.2.0"

lune-utils = { version = "0.3.4", path = "../lune-utils" }
